DATASETS:
  TEST: !!python/tuple
  - voc_2007_test_all1
  TRAIN: !!python/tuple
  - voc_2007_trainval_all1_2shot_seed15
INPUT:
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
MODEL:
  BACKBONE:
    FREEZE: true
  MASK_ON: false
  PROPOSAL_GENERATOR:
    FREEZE: true
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    FREEZE_FEAT: true
    NUM_CLASSES: 20
    OUTPUT_LAYER: CosineSimOutputLayers
  WEIGHTS: checkpoints/voc/faster_rcnn/R_50/faster_rcnn_R_50_FPN_base1/model_reset_surgery.pth
OUTPUT_DIR: ./checkpoints/voc/faster_rcnn/R_50/seed15/faster_rcnn_R_50_FPN_ft_all1_2shot
SOLVER:
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 800
  IMS_PER_BATCH: 16
  MAX_ITER: 8000
  STEPS: !!python/tuple
  - 7000
  WARMUP_ITERS: 0
_BASE_: ../../../../Base-RCNN-FPN.yaml
